name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook via Curl
        env:
          GH_SECRET: ${{ secrets.GH_SECRET }}
          WEBHOOK_URL: "https://denys-personal-source.space/deploy"
        run: |
          PAYLOAD='{"ref": "${{ github.ref }}", "repository": "${{ github.repository }}"}'
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$GH_SECRET" | sed 's/^.* //')
          
          echo "--- Sending request to $WEBHOOK_URL ---"
          
          # Флаг --fail заставит экшен упасть, если сервер ответит 4xx или 5xx
          # Флаг -i выведет заголовки ответа в логи GitHub
          curl --fail -i -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
            -d "$PAYLOAD"
